services:
  - type: web
    name: cgis-pekanbaru
    env: php
    buildCommand: composer install --no-dev && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        value: base64:0Arvn8i0I3CIWspqySzimxomDrkQyPgt5zDIEpCiaRY=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
